site_name: vest
site_url: 'https://foxssake.github.io/vest/'
theme:
  name: material
  logo: assets/vest-logo.png
  favicon: assets/vest-favicon.png
  palette:
    scheme: slate
plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        enabled: false
      interaction:
        enabled: false
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra:
  version:
    provider: mike
nav:
  - 'index.md'
  - 'Getting Started':
    - 'getting-started/installing-vest.md'
    - 'getting-started/your-first-test.md'
  - 'User Guide':
    - 'user-guide/writing-tests.md'
    - 'user-guide/test-outcomes.md'
    - 'user-guide/assertions.md'
    - 'user-guide/editor-commands.md'
    - 'user-guide/parameterized-tests.md'
    - 'user-guide/lifecycle-hooks.md'
    - 'user-guide/mocks.md'
    - 'user-guide/benchmarking.md'
    - 'user-guide/capturing-signals.md'
    - 'user-guide/coroutines.md'
    - 'user-guide/printing-custom-messages.md'
    - 'user-guide/testing-in-the-scene-tree.md'
    - 'user-guide/custom-types.md'
    - 'user-guide/project-settings.md'
    - 'user-guide/exporting-projects.md'
    - 'user-guide/running-from-ui.md'
    - 'user-guide/running-tests-selectively.md'
    - 'user-guide/running-from-cli.md'
    - 'user-guide/running-on-ci.md'
